- name: install and run nginx
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansinle.builtin.package:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

    
