- name: variables from files
  hosts: local
  connection: local
  vars_files:
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Listener is {{ LISTENER}}"