- name: variables through prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
  - name: DURATION
    prompt: please enter duration 
  - name: LISTENER
    prompt: plase enter listener name
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Listener is {{ LISTENER}}"