- name: variables through prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false
  - name: DURATION
    prompt: please enter duration 
    private: false
  - name: LISTENER
    prompt: plase enter listener name
    private: false
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Listener is {{ LISTENER}}"