- name: filtes
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('laxman') }}"


  - name: convert string to list
    vars:
      fruits: "banana,orange,apple"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',')}}"

  - name: Touch files with an optional mode
  ansible.builtin.file:
    dest: "{{ item.path }}"
    state: touch
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - path: /tmp/foo
    - path: /tmp/bar
    - path: /tmp/baz
      mode: "0444"