- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    vpc_subnet_id: subnet-01d704f7bec211287
    instance_type: t3.micro
    image_id: ami-09c813fb71547fc4f 
    security_group: sg-03bf2f0215982b4f0
    zone: lakshman.site
    instances:
    - mysql
    - backend
    - frontend
  tasks: 
  - name: install AWS python libraries
    ansible.builtin.pip:
      name: "{{ item}}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 istances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image_id }}"
      security_group: "{{ security_group }}"  
    loop: "{{ instances }}"
    register: ec2_info

  # - name: print ec2-info
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_info }}"

  - name: print the private_ip_addresses
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: print private ip r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instanses[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"


