- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120hrs
    LISTENER: Lakshman
  tasks: 
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Listener is {{ LISTENER }}"